name: pufoe_notes
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  share: ^2.0.4
  open_mail_app: ^0.4.5
  internet_file: any
  pdfx: ^2.2.0
  store_redirect: ^2.0.1
  url_launcher: ^6.1.5
  google_mobile_ads: ^2.0.0
  upgrader: any
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  
  assets:
    - assest/img/
    - assest/files/syllabus/computer/
    - assest/files/syllabus/civil/
    - assest/files/syllabus/electrical/
    - assest/files/syllabus/electronics/

